# Generated by Django 5.2 on 2025-05-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('actif', models.BooleanField(default=False, verbose_name="Créer aussi l'examen de cette matiére")),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.matiere')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.semestreexamen')),
            ],
            options={
                'verbose_name': '-> DEVOIRS',
                'verbose_name_plural': '-> DEVOIRS',
                'unique_together': {('session', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.matiere')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.semestreexamen')),
            ],
            options={
                'verbose_name': '-> EXAMENS',
                'verbose_name_plural': '-> EXAMENS',
                'unique_together': {('session', 'matiere')},
            },
        ),
    ]
