# Generated by Django 5.2 on 2025-05-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='lieu_naissance',
        ),
    ]
