# Generated by Django 5.2 on 2025-05-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0002_remove_etudiant_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='lieu_naissance',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
