# Generated by Django 5.2 on 2025-05-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0003_etudiant_date_naissance_etudiant_lieu_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='creer_classe',
            field=models.BooleanField(default=True, help_text='Créer automatiquement les classes pour cette filière ? (L1, L2, L3)'),
        ),
    ]
