# Generated by Django 5.2 on 2025-05-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0004_filiere_creer_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='creer_classe',
            field=models.BooleanField(default=False, help_text='Créer automatiquement les classes pour cette filière ? (L1, L2, L3)'),
        ),
    ]
