# Generated by Django 5.2 on 2025-06-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0005_alter_filiere_creer_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='montant',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Montant des frais de scolarité', max_digits=10),
        ),
    ]
