# Generated by Django 5.2 on 2025-05-23 17:34

import django.db.models.deletion
import gestion_des_inscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantLambda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.TextField()),
                ('date_naissance', models.DateField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.filiere')),
            ],
            options={
                'verbose_name': "Demande d'inscription",
                'verbose_name_plural': "Demandes d'inscription",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(default=gestion_des_inscriptions.models.get_annee_academique, max_length=9)),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.classe')),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_des_inscriptions.etudiantlambda')),
                ('etudiant_cree', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametre.etudiant')),
            ],
            options={
                'verbose_name': "Validation d'inscription",
                'verbose_name_plural': "Validations d'inscription",
            },
        ),
    ]
