# Generated by Django 5.2 on 2025-06-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_des_inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('filiere_souhaitee', models.CharField(max_length=100)),
                ('dernier_diplome', models.CharField(max_length=100)),
                ('annee_obtention', models.PositiveIntegerField()),
                ('dernier_etablissement', models.CharField(max_length=150)),
                ('adresse_complete', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('motivation', models.TextField()),
                ('possede_ordinateur', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PreInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('filiere_souhaitee', models.CharField(max_length=100)),
            ],
        ),
    ]
