# Generated by Django 5.2 on 2025-06-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_des_inscriptions', '0002_dossieretudiant_preinscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossieretudiant',
            options={'verbose_name': "DEMANDE D'INSCRIPTION | INSCRIPTION COMPLETE", 'verbose_name_plural': "DEMANDE D'INSCRIPTION | INSCRIPTION COMPLETE"},
        ),
        migrations.AlterModelOptions(
            name='preinscription',
            options={'verbose_name': "DEMANDE D'INSCRIPTION | PRE-INSCRIPTION", 'verbose_name_plural': "DEMANDE D'INSCRIPTION | PRE-INSCRIPTION"},
        ),
    ]
