# Generated by Django 5.2 on 2025-06-27 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametre', '0005_alter_filiere_creer_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('inscription', "Attestation d'inscription"), ('frequentation', 'Attestation de fréquentation')], max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('valide', models.BooleanField(default=True)),
                ('numero', models.CharField(help_text="Numéro d'identification de l'attestation", max_length=20, unique=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='parametre.etudiant')),
            ],
            options={
                'verbose_name': 'Liste des attestations',
                'verbose_name_plural': 'Liste des attestations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
