# Generated by Django 5.2 on 2025-05-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parametre.semestreexamen')),
            ],
            options={
                'verbose_name': 'PARAMÈTRE RÉSULTAT | SÉLECTIONNEZ UN SEMESTRE',
                'verbose_name_plural': 'PARAMÈTRE RÉSULTAT | SÉLECTIONNEZ UN SEMESTRE',
            },
        ),
        migrations.CreateModel(
            name='MatiereRattrapage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.classe')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.semestreexamen')),
            ],
            options={
                'verbose_name': 'RATTRAPAGE | MATIERE RATTRAPAGE PAR CLASSE ET SESSION',
                'verbose_name_plural': 'RATTRAPAGE | MATIERE NON VALIDÉE PAR CLASSE ET SESSION',
                'unique_together': {('classe', 'session')},
            },
        ),
        migrations.CreateModel(
            name='ResultatAdmissionClasseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.classe')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.semestreexamen')),
            ],
            options={
                'verbose_name': "RÉSULTAT D'ADMISSION PAR CLASSE ET SESSION",
                'verbose_name_plural': "RÉSULTATS D'ADMISSION PAR CLASSE ET SESSION",
                'unique_together': {('classe', 'session')},
            },
        ),
        migrations.CreateModel(
            name='ResultatEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_generale', models.FloatField(blank=True, default=0, editable=False, null=True)),
                ('mention', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.etudiant')),
            ],
            options={
                'verbose_name': 'LISTE DES BULLETINS | RÉSULTATS DES ÉTUDIANTS',
                'verbose_name_plural': 'LISTE DES BULLETINS | RÉSULTATS DES ÉTUDIANTS',
                'ordering': ['-moyenne_generale'],
                'unique_together': {('etudiant', 'moyenne_generale')},
            },
        ),
    ]
