# Generated by Django 5.2 on 2025-06-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraisscolarite',
            name='reste_a_payer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Reste à payer'),
        ),
    ]
