# Generated by Django 5.2 on 2025-06-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_fraisscolarite_reste_a_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraisscolarite',
            name='is_complet',
            field=models.BooleanField(default=False, editable=False, verbose_name='Paiement total ? '),
        ),
        migrations.AlterField(
            model_name='fraisscolarite',
            name='reste_a_payer',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Reste à payer'),
        ),
    ]
