# Generated by Django 5.2 on 2025-06-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_fraisscolarite_is_complet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraisscolarite',
            name='date_paiement',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date de dernier paiement'),
        ),
    ]
